#!/bin/sh
# Call Jenkins to start build and pass environment parameter
#
echo "executing post-receive hook"

# Curl POST request using jenkins user with API token
curl http://51.254.132.239:8082/job/Github%20Charts/build?delay=20sec
